### ISSUE TITLE
Hey how would I get this working.

### ISSUE THREAD

**Issue by GhostieSpook** [riverrrrrr/anilist-Liker#1]
I know it sounds dumb, buuuutt. I'm wondering if you just add it manually as an extension on chrome or whatnot?

**Comment by riverrrrrr** [comment]
Hey there! I should add some links in the readme but the extension is on [Chrome ](https://chrome.google.com/webstore/detail/anilist-liker/mkecceglggaoclfnhlgogoanmnmjelcn)and [Firefox](https://addons.mozilla.org/en-US/firefox/addon/anilist-liker/)!
